<?php $page_title='Obchodné podmienky pre e-shop'; include '_inc/head.php';
include '_inc/header.php'; ?>

    <section class="banner_area">
        <div class="container">
            <div class="banner_text">
                <h3>Obchodné podmienky</h3>
                <ul>
                    <li><a href="index.php">Domov</a></li>
                    <li><a href="#">Obchodné podmienky</a></li>
                </ul>
            </div>
        </div>
    </section>
    <!--================End Main Header Area =================-->

    <!--================Product Area =================-->
    <section class="p_100">
        <div class="container">
            <div class="row product_inner_row">
                <div class="col-lg-12">
                    <div class="row">
                       <p><b style="font-size: 20px; text-align: center;">Obchodné podmienky pre e-shop</b><br>
                        <b>Účelom týchto obchodných podmienok je vymedziť a upresniť práva a povinnosti predávajúceho (dodávateľa) na jednej strane a kupujúceho (zákazníka, spotrebiteľa) na strane druhej. Všetky zmluvné vzťahy medzi predávajúcim a kupujúcim sú uzatvorené v súlade s právnym poriadkom Slovenskej republiky. V prípade ak je zmluvnou stranou spotrebiteľ, riadia sa právne vzťahy neupravené týmito obchodnými podmienkami zákonom č. 40/1964 Zb. Občiansky zákonník v platnom znení, zákonom č. 250/2007 Z. z. o ochrane spotrebiteľa v platnom znení, zákonom č. 108/2000 Z. z. o ochrane spotrebiteľa pri domovom predaji a zásielkovom predaji v platnom znení. V prípade, ak je zmluvnou stranou podnikateľ, riadia sa právne vzťahy neupravené týmito obchodnými podmienkami, zákonom č. 513/1991 Zb. Obchodný zákonník v platnom znení.</b><br><br>
                           <b>1. Definícia</b><br>
                           1.1	V týchto Obchodných podmienkach.<br>
                           1.1.1 <b>„E-shop“</b> znamená počítačový program - internetová aplikácia, ktorá je dostupná v sieti Internet prostredníctvom internetovej adresy www.tart.sk, ktorej hlavnou funkcionalitou je zobrazenie, výber a objednanie tovaru Uživateľom;<br>
                           1.1.2 <b>„Spotrebiteľská zmluva“</b> je Kúpna zmluva, ak zmluvnými stranami sú na jednej strane dodávateľ a na druhej strane spotrebiteľ;<br>
                           1.1.3 <b>„Predávajúci“</b> (dodávateľ) osoba, ktorá pri uzatváraní a plnení spotrebiteľskej zmluvy koná v rámci predmetu svojej obchodnej alebo inej podnikateľskej činnosti. Je to podnikateľ, ktorý spotrebiteľovi ponúka alebo predáva výrobky alebo poskytuje služby a taktiež podnikateľ, ktorý priamo alebo prostredníctvom iných podnikateľov dodáva kupujúcemu výrobok;<br>
                           1.1.4 <b>„Spotrebiteľ“</b> (kupujúci) je osoba, ktorá nakupuje výrobky alebo používa služby pre osobnú potrebu alebo pre príslušníkov svojej domácnosti, a ktorá pri uzatváraní a plnení spotrebiteľskej zmluvy nekoná v rámci predmetu svojej obchodnej alebo inej podnikateľskej činnosti;<br>
                           1.1.5 Kupujúci, ktorý nie je spotrebiteľom je osoba, ktorá pri uzatváraní a plnení kúpnej zmluvy koná v rámci svojej obchodnej alebo inej podnikateľskej činnosti;<br>
                           1.1.6 Uzatvorenie kúpnej zmluvy - objednávka kupujúceho predstavuje návrh na uzatvorenie kúpnej zmluvy. Samotná kúpna zmluva je uzatvorená momentom doručenia záväzného súhlasu predávajúceho s návrhom kúpnej zmluvy kupujúcemu, t.j. záväzným potvrdením objednávky zo strany predávajúceho. Od tohto momentu medzi predávajúcim a kupujúcim vznikajú vzájomné práva a povinnosti, ktoré sú vymedzené kúpnou zmluvou a týmito obchodnými podmienkami. Obchodné podmienky sú neoddeliteľnou súčasťou kúpnej zmluvy;<br>
                           1.1.7 <b>„Nákupný košík"</b> znamená časť E-shopu, ktorá je automaticky generovaná aktiváciou príslušných funkcií Uživateľom v rámci jeho konania v užívateľskom prostredí E-shopu, najmä pridaním alebo odebraním Tovaru, resp. Služby/alebo zmenou množstva vybraného Tovaru, resp. Služby;<br>
                           1.1.8 <b>„Občiansky zákonník“</b> znamená zákon číslo 40/1964 Zb., Občiansky zákonník v platnom znení;<br>
                           1.1.9 <b>„Prevádzkovateľ“</b> znamená spoločnosť Tart cake studio s. r. o., IČO: 53447964, so sídlom Potočná ulica 1598/1, 97703 Brezno;<br>
                           1.1.10 <b>„Prístupové údaje“</b> znamenajú unikátne prihlasovacie meno a k nemu priradené heslo vložené Uživateľom do databázy E-shopu pri Registrácii;<br>
                           1.1.11 <b>„Tovar“</b> znamená vec ponúkanú Prevádzkovateľom k predaju Užívateľovi prostredníctvom E-shopu a ak je k Tovaru ponúkaná, tak aj licencia k užívaniu tejto veci;<br><br>
                           <b>2	Proces uzatvorenia Zmluvy</b><br>
                           2.1	Prevádzkovateľ prostredníctvom E-shopu ponúka Užívateľom uzatvorenie Kúpnej zmluvy. Ponukou na uzatvorenie Kúpnej zmluvy zo strany Prevádzkovateľa je zobrazenie tlačítka s označením „Dokončiť objednávku“ v užívateľskom rozhraní E-shopu.<br>
                           2.2	Za bezvýhradné prijatie ponuky Prevádzkovateľa na uzatvorenie Kúpnej zmluvy podľa odst. 2.1 týchto Obchodných podmienok zo strany Užívateľa sa považuje kliknutie na dané tlačítko s označením „Dokončiť objednávku“.<br>
                           2.3	Bezvýhradným prijatím ponuky podľa odst. 2.2 týchto Obchodných podmienok je uzatvorená Kúpna zmluva.<br>
                           2.4	Zmluva je uzatvorená momentom, kedy elektronická informácia o kliknutí na tlačítko „Dokončiť objednávku“ Užívateľom dôjde prostredníctvom siete Internet na server, kde je nainštalovaný E-shop.<br>
                           2.5	Užívateľ sa zaväzuje do príslušných textových polí v užívateľskom prostredí E-shopu vyplniť pravdivé a úplné údaje, najmä pravdivo vyplniť svoju emailovou adresu, identifikačné údaje a prípadne dodaciu adresu. Užívateľ berie na vedomie, že Prevádzkovateľ bude ním zadané údaje dôvodne považovať za správne a úplné a nie je povinný a ani oprávnený zadané údaje kontrolovať.<br>
                           2.6	Prevádzkovateľ zašle Užívateľovi emailovou správu o uzatvorení Kúpnej zmluvy, a to na emailovú adresu zadanú Užívateľom do príslušného poľa v užívateľskom prostredí E-shopu.<br><br>
                           <b>3	Kúpna zmluva</b><br>
                           3.1	Uzatvorením Kúpnej zmluvy sa stávajú účinné nasledujúce ustanovenia:<br>
                           3.1.1	Užívateľ kupuje od Prevádzkovateľa Tovar, ktorý si Užívateľ zvolil v užívateľskom prostredí E-shopu vložením do Nákupného košíka, a to v množstve, ktoré si Užívateľ zvolil a/alebo nastavil u daného Tovaru v užívateľskom prostredí E-shopu a Užívateľ sa zaväzuje zaplatiť Prevádzkovateľovi za daný Tovar cenu, ktorá je uvedená pri takomto Tovare v užívateľskom prostredí E-shopu.<br>
                           3.1.2	Prevádzkovateľ má právo až do momentu odoslania Tovaru Užívateľovi od Kúpnej zmluvy odstúpiť, a to z akéhokoľvek dôvodu alebo bez uvedenia dôvodu. Za odstúpenie od Kúpnej zmluvy sa považuje aj právne konanie Prevádzkovateľa spočívajúce v oznámení Užívateľovi, že ním objednaný Tovar nemožno dodať.<br>
                           3.1.3	Prevádzkovateľ je oprávnený kedykoľvek požiadať Užívateľa o dodatočné potvrdenie objednávky a do doby, než obdrží od Užívateľa potvrdenie objednávky, je oprávnený pozdržať odoslanie Tovaru Užívateľovi.<br>
                           3.1.4	Spôsob zabalenia Tovaru určuje výhradne Prevádzkovateľ.<br>
                           3.1.5	Užívateľ je povinný zaplatiť Prevádzkovateľovi náklady spojené s balením a doručením daného tovaru Užívateľovi a to vo výške uvedenej u danej objednávky v užívateľskom prostredí E-shopu.<br>
                           3.1.6	Užívateľ má právo zvoliť z možností zobrazených Užívateľovi v užívateľskom prostredí E-shopu spôsob zaplatenia kúpnej ceny za Tovar a prípadne ďalšie peňažné plnenia Prevádzkovateľovi.<br>
                           3.1.7	Pokiaľ niektorý zo spôsobov platby obsahuje informácie o nákladoch na prevedenie takejto platby, je Užívateľ povinný znášať náklady na prevedenie tejto platby, ktoré sú uvedené pri danej platbe v užívateľskom prostredí E-shopu.<br>
                           3.1.8	V prípade bezhotovostnej platby bankovým prevodom je Užívateľ povinný uviesť variabilný symbol určený Prevádzkovateľom.<br>
                           3.1.9	V prípade bezhotovostnej platby je povinnosť Užívateľa zaplatiť kúpnu cenu splnená momentom pripísania príslušnej čiastky na bankový účet určený Prevádzkovateľom.<br>
                           3.1.10	Prevádzkovateľ má právo poskytnúť Užívateľovi zľavu z ceny Tovaru. Zľavy z ceny Tovaru možno vzájomne kombinovať, pokiaľ nie je u konkrétnej zľavy uvedené výslovne inak.<br>
                           3.1.11	Súčasťou kúpnej ceny za Tovar nie sú žiadne platby, poplatky alebo iné odmeny, ktoré musí Užívateľ vynaložiť na služby poskytnuté tretím stranámi v súvislosti so zaplatením kúpnej ceny za Tovar; tieto náklady sú výhradne nákladmi Užívateľa.<br>
                           3.1.12	Prevádzkovateľ si vyhradzuje vlastnícke právo k Tovaru, ktorý je predmetom Kúpnej Zmluvy až do úplného zaplatenia kúpnej ceny za daný Tovar Užívateľom.<br>
                           3.1.13	Prevádzkovateľ sa zaväzuje dodať Tovar Užívateľovi v primeranej lehote od uzatvorenia Kúpnej zmluvy. Všetky lehoty pre dodanie Tovaru uvedené v užívateľskom rozhraní E-shopu sú len orientačné.<br>
                           3.1.14	Prevádzkovateľ zašle vždy Užívateľovi daňový doklad - faktúru v elektronickej podobe, a to na emailovou adresu Užívateľa zadanú pri danej objednávke do Užívateľského prostredia E-shopu.<br>
                           3.1.15	Ak je Prevádzkovateľom spoločne s Tovarom poskytnutý Užívateľovi dar, je darovacia zmluva medzi Užívateľom a Prevádzkovateľom uzatvorená s rozväzovacou podmienkou, že ak dôjde k odstúpeniu od Kúpnej zmluvy, ruší sa daná darovacia zmluva bez ďalšieho od počiatku spolu s kúpnou zmluvou a Užívateľ je povinný spolu so zakúpeným  tovarom Prevýdzkovateľovi vrátiť aj poskytnutý dar.<br>
                           3.1.16	Prevádzkovateľ poskytuje Užívateľovi na zakúpený Tovar záruku, ak je záručná doba uvedená pri  danom Tovare v užívateľskom prostredí E-shopu, a to po dobu uvedenej záručnej doby, pričom takto uvedená záruka platí iba pre Spotrebiteľov.<br>
                           3.1.17	Práva z vadného plnenia je Užívateľ oprávnený uplatniť u Prevádzkovateľa na adrese jeho sídla a/alebo prevádzky. Za moment uplatnenia reklamácie sa považuje okamih, kedy Prevádzkovateľ obdrží od Užívateľa reklamovaný Tovar.<br>
                           3.1.18	Ak je v rámci užívateľského prostredia E-shopu pri danom Tovare uvedené, že je použitý, kupuje Užívateľ Tovar v použitom stave, vrátane uvedených vád tohto Tovaru.<br>
                           3.1.19	Nebezpečenstvo straty, poškodenia a/alebo zničenia Tovaru, ktorý je predmetom Kúpnej zmluvy prechádza na Užívateľa, ktorý je Spotrebiteľom, momentom prevzatia daného tovaru Užívateľom.<br>
                           3.1.20	Nebezpečenstvo straty, poškodenia a/alebo zničenia Tovaru, ktorý je predmetom Zmluvy prechádza na Užívateľa, ktorý nie je Spotrebiteľom, momentom prevziatia daného tovaru Užívateľom.<br><br>
                           <b>4	Informácie pre Spotrebiteľa</b><br>
                           4.1	Spotrebiteľ má právo od Kúpnej zmluvy odstúpiť, a to do štrnástich (14) dní od prevzatia Tovaru. V prípade, že predmetom Kúpnej zmluvy je niekoľko druhou Tovaru alebo dodanie niekoľkých častí, plynie táto lehota odo dňa prevzatia poslednej dodávky Tovaru. Odstúpenie od Kúpnej zmluvy musí byť Prevádzkovateľovi (ako predávajúcemu) odoslané v lehote uvedenej v tomto odstavci.<br>
                           4.2	Ak odstúpi Spotrebiteľ od Kúpnej zmluvy, je povinný oznámiť písomne číslo svojho bankového účtu pre vrátenie kúpnej ceny za Tovar, ktorá môže byť znížená ak sú na to splnené zákonné dôvody.<br>
                           4.3	Ak odstúpi Spotrebiteľ od Kúpnej zmluvy ohľadne Tovaru, ktorý vracia Prevádzkovateľovi poškodený a/alebo opotrebovaný, najmä pokiaľ sú odstránené originálne označenia Tovaru (t.j. ceduľky, nálepky a pod.), je Spotrebiteľ povinný Prevádzkovateľovi nahradiť náklady na uvedenie Tovaru do pôvodného stavu.<br>
                           4.4	V prípade odstúpenia Spotrebiteľa od Kúpnej zmluvy je Prevádzkovateľ povinný vrátiť Spotrebiteľovi kúpnu cenu bez zbytočného odkladu, najneskôr do 14 dní odo dňa, kedy bol informovaný o rozhodnutí Spotrebiteľa odstúpiť od danej Kúpnej zmluvy.<br>
                           4.5	Pokiaľ Spotrebiteľ na základe Kúpnej zmluvy obdržal Tovar tvorený hnuteľnými vecami, je povinný ho bez zbytočného odkladu, najneskôr do 14 dní odo dňa, kedy došlo k odstúpeniu od danej Kúpnej zmluvy, zaslať späť Prevádzkovateľovi alebo ho odovzdať na adrese prevádzky alebo sídla Prevádzkovateľa. Lehota sa považuje za zachovanú aj pokiaľ budú hnuteľné veci odoslané Prevádzkovateľovi najneskôr posledný deň vyššie uvedenej lehoty.<br>
                           4.6	Spotrebiteľ zodpovedá Prevádzkovateľovi za zníženie hodnoty Tovaru v dôsledku nakladania s týmto tovarom iným spôsobom, než ktorý je nutný k oboznámeniu sa s povahou a vlastnosťami daného Tovaru, vrátane jeho funkčnosti.<br>
                           4.7	Formulár pre odstúpenie od Kúpnej Zmluvy tvorí prílohu č. 1 týchto Obchodných podmienok.<br>
                           4.8	Prevádzkovateľ využívá možnosť mimosúdneho riešenia sťažností spotrebiteľov. V prípade sťažnosti sa môžu Spotrebitelia bezplatne obrátiť na príslušného pracovníka Prevádzkovateľa prostredníctvom emailové adresy info@tart.sk.<br>
                           <b>5	Reklamačný poriadok</b><br>
                           5.1	Prevádzkovateľ zodpovedá Spotrebiteľovi, že Tovar je pri prevzatí bez vád. To neplatí ak je predmetom Kúpnej zmluvy tovar s vadami, ktoré je Prevádzkovateľ, ak sú mu známe, alebo s prihliadnutím na všetky okolnosti mu mali byť známe, povinný oznámiť Spotrebiteľovi.<br>
                           5.2	Ak obsahuje Tovar vady, má Spotrebiteľ právo požadovať dodanie nového Tovaru bez vád, pokiaľ to nie je vzhľadom k povahe vady neprimerané, alebo pokiaľ bol predmetom Kúpnej zmluvy Tovar s vadami, ktoré Prevádzkovateľ, ak mu boli vady známe, alebo s prihliadnutím na všetky okolnosti mali byť známe, oznámil Spotrebiteľovi. Pokiaľ sa vada týka iba súčasti Tovaru, môže Spotrebiteľ požadovať len výmenu danej súčasti tovaru; ak to nie je možné, má právo odstúpiť od Kúpnej zmluvy.<br>
                           5.3	Právo na dodanie nového Tovaru, alebo výmenu súčasti tovaru má Spotrebiteľ aj v prípade odstrániteľnej vady, pokiaľ nemôže daný Tovar riadne užívať pre opakovaný výskyt vady po oprave alebo pre väčší počet vád. V takomto prípade má Spotrebiteľ právo od Kúpnej zmluvy odstúpiť.<br>
                           5.4	Ak Spotrebiteľ od Kúpnej zmluvy neodstúpi alebo si neuplatní právo na dodanie nového Tovaru bez vád, ani na výmenu jeho súčasti alebo na opravu Tovaru, môže požadovať primeranú zľavu z ceny Tovaru. Spotrebiteľ má právo na primeranú zľavu z ceny Tovaru aj v prípade, že mu Prevádzkovateľ nemôže dodať nový Tovar bez vád, vymeniť jeho súčasť alebo Tovar opraviť, ako aj v prípade, že Prevádzkovateľ nezjedná nápravu v primeranej dobe, alebo ak by zjednanie nápravy spôsobilo Spotrebiteľovi značné obtiaže.<br>
                           5.5	Právo z vadného plnenia Spotrebiteľovi neprináleží, pokiaľ Spotrebiteľ pred prevzatím Tovaru vedel, že Tovar má vadu, alebo pokiaľ Spotrebiteľ vadu sám spôsobil.<br>
                           5.6	Zodpovednosť Prevádzkovateľa za vady Tovaru sa nevzťahuje na opotrebenie Tovaru spôsobené jeho obvyklým užívaním, pri Tovare predávanom za nižšiu kúpnu cenu na vadu, pre ktorú bola nižšia kúpna cena dohodnutá, pri použitom Tovare na vadu zodpovedajúcu miere používania alebo opotrebenia, ktorú Tovar mal pri prevzatí Spotrebiteľom, alebo ak to vyplýva z povahy Tovaru.<br>
                           5.7	Ak je na Tovar poskytovaná záruka, Spotrebiteľ má právo uplatniť zodpovednosť z vadného plnenia v záručnej dobe.<br>
                           5.8	Na žiadosť Spotrebiteľa je Prevádzkovateľ povinný poskytnúť Spotrebiteľovi záručný list. Ak to povaha Tovaru umožňuje, postačuje namiesto záručného listu vydať Spotrebiteľovi doklad o zakúpení Tovaru obsahujúci údaje, ktoré musí obsahovať záručný list.<br>
                           5.9	V prípade, že Spotrebiteľ využije svoje právo na odstránenie vád Tovaru jeho opravou, pri Tovare, pri ktorom je pre účely záručných opráv  určený podnikateľ odlišný od Prevádzkovateľa, ktorého sídlo alebo miesto podnikania je v rovnakom mieste ako v prípade Prevádzkovateľa alebo v mieste pre Spotrebiteľa bližšom, uplatní Spotrebiteľ právo na záručnú opravu u tohoto podnikateľa.<br>
                           5.10	Reklamácia Tovaru, vrátane odstránenia vád daného Tovaru, musí byť vybavená bez zbytočného odkladu, najneskôr do 30 dní odo dňa uplatnenia reklamácie, pokiaľ sa Prevádzkovateľ so Spotrebiteľom nedohodnú na dlhšej lehote. Po uplynutí tejto lehoty má Spotrebiteľ rovnaké práva, akoby sa jednalo o podstatné porušenie Zmluvy.<br>
                           5.11	Lehota na vybavenie reklamácie neplynie v prípade, že Prevádzkovateľ neobdržal od Spotrebiteľa všetky podklady potrebné pre vybavenie danej reklamácie, a to do doby, než budú dané podklady dodané.<br>
                           5.12	Prevádzkovateľ alebo ním určený subjekt po riadnom vybavení danej reklamácie vyzve Spotrebiteľa k prevzatiu opraveného Tovaru.<br>
                           5.13	Nárok na uplatnenie práv z vád Tovaru zaniká v prípade neodbornej montáže alebo neodborného uvedenia Tovaru do prevádzky, rovnako ako pri neodbornom zaobchádzaní s ním, t.j. najmä pri používaní Tovaru v podmienkach, ktoré nezodpovedajú svojimi parametrami parametrom uvedeným v dokumentácii k Tovaru.<br><br>
                           <b>6	Alternatívne riešenie sporov</b><br>
                           6.1	Objednávateľ – Spotrebiteľ – má právo obrátiť sa na Prevádzkovateľa - predávajúceho so žiadosťou o nápravu e-mailom na info@tart.sk ak nie je spokojný so spôsobom, ktorým Predávajúci vybavil jeho reklamáciu alebo ak sa domnieva, že predávajúci porušil jeho práva. Ak predávajúci odpovie na túto žiadosť zamietavo alebo na ňu neodpovie do 30 dní od jej odoslania, Spotrebiteľ má právo podať návrh na začatie alternatívneho riešenia sporu subjektu alternatívneho riešenia sporov (ďalej len subjekt ARS) podľa zákona 391/2015 Z. z. ARS subjektmi sú orgány a oprávnené právnické osoby podľa § 3 zákona č. 391/2015 Z. z. Návrh môže Spotrebiteľ podať spôsobom určeným podľa § 12 zákona č. 391/2015 Z. z.<br>
                           6.2	Spotrebiteľ môže podať sťažnosť aj prostredníctvom platformy alternatívneho riešenia sporov RSO, ktorá je dostupná on-line na: http://ec.europa.eu/consumers/odr/index_en.htm.<br>
                           6.3	Alternatívne riešenie sporov môže využiť len Spotrebiteľ – fyzická osoba, ktorá pri uzatváraní a plnení spotrebiteľskej zmluvy nekoná v rámci predmetu svojej podnikateľskej činnosti, zamestnania alebo povolania. Alternatívne riešenie sporov sa týka len sporu medzi Spotrebiteľom a Predávajúcim, vyplývajúceho zo spotrebiteľskej zmluvy alebo súvisiaceho so spotrebiteľskou zmluvou. Alternatívne riešenie sporov sa týka len zmlúv uzatvorených na diaľku. Alternatívne riešenie sporov sa netýka sporov, kde hodnota sporu neprevyšuje sumu 20 EUR. Subjekt ARS môže od Spotrebiteľa požadovať úhradu poplatku za začatie alternatívneho riešenia sporu maximálne do výšky 5 EUR s DPH.<br>
                           <br>
                           <b>7	Ochrana osobných údajov</b><br>
                           7.1	Pri spracúvaní osobných údajov Prevádzkovateľ postupuje podľa Nariadenia Európskeho parlamentu a Rady (EÚ) 2016/679 z 27.4.2016 o ochrane fyzických osôb pri spracúvaní osobných údajov a o voľnom pohybe takýchto údajov, ktorým sa zrušuje smernica 95/46/ES (ďalej len „GDPR“) a zákona č. 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov.<br>
                           7.2	Podrobné informácie o tom, ako zhromažďujeme, spracúvame a chránime osobné údaje našich zákazníkov pri využívaní našich služieb sú upravené v zásadách ochrany osobných údajov.<br><br>
                           <b>8	Cookies</b><br>
                           Prevádzkovateľ týmto informuje Užívateľa, že spracováva súbory cookies Užívateľa, vrátane trvalých súborov cookies a Užívateľ s týmto vyslovuje svoj súhlas.<br>
                           Súhlas podľa predchádzajúceho odstavca je udelený na dobu 2 mesiacov/mesiaca.<br>
                           Prevádzkovateľ spracováva súbory cookies Užívateľa k personalizácií obsahu a reklám, k využívaniu funkcií sociálnych médií a analýzy návštevnosti. Prevádzkovateľ Informácie o tom, ako E-shop Užívateľ používa, zdieľa so svojimi partnermi pôsobiacimi v oblasti sociálnych médií, inzercie a analýz.<br><br>
                           <b>9	Užívanie E-shopu</b><br>
                           9.1	Prevádzkovateľ týmto udeľuje Užívateľovi nevýhradnú licenciu k užívaniu E-shopu spôsobom predvídaným týmito Obchodnými podmienkami.<br>
                           9.2	Prevádzkovateľ má právo zmeniť E-shop, teda jeho technické riešenie a/alebo užívateľské rozhranie.<br>
                           9.3	Prevádzkovateľ má právo obmedziť alebo prerušiť funkčnosť E-shopu prípadne prístup k nemu na dobu nevyhnutnú z dôvodu údržby alebo opravy E-shopu.<br>
                           9.4	Užívateľ je povinný dodržovať pri užívaní E-shopu platné a účinné právne predpisy Slovenskej republiky a Európskeho spoločenstva. Akúkoľvek škodu, ktorá by porušením tejto povinnosti Užívateľa Prevádzkovateľovi alebo tretím osobám vznikla, je Užívateľ povinný nahradiť v plnom rozsahu.<br>
                           9.5	V prípade porušenia týchto Obchodných podmienok alebo Kúpnej zmluvy alebo platných a účinných právnych predpisov má Prevádzkovateľ právo zrušiť Užívateľský účet.<br><br>
                           <b>10	Prehlásenia Prevádzkovateľa</b><br>
                           10.1	Prevádzkovateľ prehlasuje, že záznamy údajov v E-shope, ako elektronickom systéme, sú spoľahlivé a sú vykonávané systematicky a sú chránené proti zmenám.<br>
                           10.2	Vplyvom technickej chyby v E-shope môže dôjsť k zobrazeniu kúpnej ceny pri Tovare, ktorej výška nezodpovedá obvyklej cene za takýto Tovar na trhu; v takomto prípade Prevádzkovateľ nemá povinnosť dodať daný Tovar za zobrazenú kúpnu cenu, kontaktuje Užívateľa a oznámi mu skutočnú kúpnu cenu daného Tovaru a Užívateľ má právo sa rozhodnúť, či Tovar za skutočnú kúpnu cenu prijme a pokiaľ sa tak nestane, ruší sa Kúpna zmluva od počiatku.<br>
                           10.3	Užívateľ berie na vedomie, že fotografie pri Tovare v E-shope môžu byť ilustrované, alebo môžu pôsobiť skresľujúcim dojmom v dôsledku ich prevedenia do zobrazenia v technickom prostriedku Užívateľa, preto je Užívateľ povinný sa vždy oboznámiť s celým popisom daného Tovaru a v prípade nejasností kontaktovať Prevádzkovateľa.<br>
                           10.4	Kontaktné údaje Prevádzkovateľa pre komunikáciu s Užívateľom sú uvedené v užívateľskom rozhraní E-shopu v sekcii Kontakt.<br><br>
                           <b>11	Právo na odstúpenie od kúpnej zmluvy</b><br>
                           11.1	Kupujúci je oprávnený odstúpiť od Kúpnej zmluvy bez udania dôvodu v súlade s ust. § 7 a nasl. Zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji na diaľku (ďalej len <b>„Zákon o ochrane spotrebiteľa pri predaji na diaľku“</b>) v lehote 14 dní od prevzatia tovaru, resp. odo dňa uzavretia zmluvy o poskytnutí služby alebo zmluvy o poskytovaní elektronického obsahu nedodávaného na hmotnom nosiči, ak Predávajúci včas a riadne splnil informačné povinnosti podľa ust. § 3 Zákona o ochrane spotrebiteľa pri predaji na diaľku.<br>
                           11.2	Kupujúci má právo v rámci tejto lehoty po prevzatí tovar rozbaliť a vyskúšať ho obdobným spôsobom ako je obvyklé pri nákupe v klasickom „kamennom“ obchode, a to v rozsahu potrebnom na zistenie vád, vlastností a funkčnosti tovaru.<br>
                           11.3	Kupujúci je povinný najneskôr do 14 dní odo dňa odstúpenia od zmluvy zaslať tovar späť alebo ho odovzdať Predávajúcemu alebo osobe poverenej Predávajúcim na prevzatie tovaru. To neplatí, ak Predávajúci navrhne, že si tovar vyzdvihne osobne alebo prostredníctvom ním poverenej osoby. Lehota podľa prvej vety sa považuje za zachovanú, ak bol tovar odovzdaný na prepravu najneskôr v posledný deň lehoty.<br>
                           11.4	Odstúpiť od zmluvy nie je možné pri tovare uzavretom v ochrannom obale, ktorý nie je vhodné vrátiť z dôvodu ochrany zdravia alebo z hygienických dôvodov a ktorého ochranný obal bol po dodaní porušený.<br>
                           11.5	V prípade, ak Kupujúci už prevzal objednaný tovar, je povinný ho vrátiť v originálnom nepoškodenom balení. V prípade, ak Kupujúci vráti objednaný tovar poškodený, čiastočne spotrebovaný resp. v stave, ktorý nezodpovedá stavu, v ktorom bol Predávajúcim odoslaný, berie na vedomie, že Predávajúci je oprávnený si takto vzniknutú škodu, ktorú je Predávajúci povinný preukázať, uhradiť zo sumy, ktorá bola uhradená kupujúcim za objednaný tovar.<br>
                           11.6	Kupujúci je zároveň povinný v odstúpení od zmluvy uviesť kontaktné údaje a číslo účtu, na ktorý má byť uhradená suma za objednaný Tovar poukázaná zo strany predávajúceho.Predávajúci je povinný bez zbytočného odkladu, najneskôr do 14 dní odo dňa doručenia oznámenia o odstúpení od zmluvy vrátiť kupujúcemu všetky platby, ktoré od neho prijal na základe zmluvy alebo v súvislosti s ňou. Predávajúci nie je povinný vrátiť Kupujúcemu tieto platby pred tým, ako mu je tovar doručený alebo kým kupujúci nepreukáže zaslanie tovaru späť predávajúcemu, ibaže predávajúci navrhne, že si tovar vyzdvihne osobne alebo prostredníctvom ním poverenej osoby.<br>
                           11.7	Ak Kupujúci odstúpi od Kúpnej zmluvy, zrušuje tá sa od počiatku, ako aj každá doplnková zmluva súvisiaca s Kúpnou zmluvou, od ktorej Kupujúci odstúpil. Od Kupujúceho nie je možné požadovať žiadne náklady alebo iné platby v súvislosti so zrušením doplnkovej zmluvy okrem úhrady nákladov a platieb uvedených v ust. § 9 ods. 3, ust. § 10 ods. 3 a 5 Zákona o ochrane spotrebiteľa pri predaji na diaľku a ceny za službu, ak je predmetom zmluvy poskytnutie služby a došlo k úplnému poskytnutiu služby.<br>
                           11.8	Kupujúci znáša náklady na vrátenie tovaru Predávajúcemu alebo osobe poverenej Predávajúcim na prevzatie tovaru. To neplatí, ak Predávajúci súhlasil, že ich bude znášať sám alebo ak si nesplnil povinnosť podľa § 3 ods. 1 písm. i) Zákona o ochrane spotrebiteľa pri predaji na diaľku.<br>
                           11.9	Kupujúci zodpovedá len za zníženie hodnoty tovaru, ktoré vzniklo v dôsledku takého zaobchádzania s Tovarom, ktoré je nad rámec zaobchádzania potrebného na zistenie vlastností a funkčnosti Tovaru. Spotrebiteľ nezodpovedá za zníženie hodnoty Tovaru, ak si Predávajúci nesplnil informačnú povinnosť o práve Spotrebiteľa odstúpiť od zmluvy podľa § 3 ods. 1 písm. h) Zákona o ochrane spotrebiteľa pri predaji na diaľku.<br>
                           11.10	V prípade, že Kupujúci odstúpi od zmluvy a doručí Predávajúcemu Tovar, ktorý je používaný, poškodený alebo neúplný, zaväzuje sa Kupujúci uhradiť Predávajúcemu hodnotu, o ktorú sa znížila hodnota Tovaru v zmysle ust. § 457 Občianskeho zákonníka v skutočnej výške a náklady, ktoré vznikli Predávajúcemu v súvislosti s opravou Tovaru a jeho uvedením do pôvodného stavu kalkulované podľa cenníka pre (po)záručný servis Tovaru. Kupujúci je povinný v zmysle tohto bodu reklamačných a obchodných podmienok uhradiť Predávajúcemu náhrady najviac vo výške rozdielu medzi kúpnou cenou Tovaru a hodnotou Tovaru v čase odstúpenia od Kúpnej zmluvy.<br>
                           11.11	V súlade s ust. § 7 ods. 6 Zákona o ochrane spotrebiteľa pri predaji na diaľku Kupujúci nemôže odstúpiť od zmluvy, ktorej predmetom je:<br>predaj tovaru zhotoveného podľa osobitných požiadaviek spotrebiteľa, tovaru vyrobeného na mieru alebo tovaru určeného osobitne pre jedného spotrebiteľa,<brpredaj tovaru uzavretého v ochrannom obale, ktorý nie je vhodné vrátiť z dôvodu ochrany zdravia alebo z hygienických dôvodov a ktorého ochranný obal bol po dodaní porušený,<br>predaj zvukových záznamov, obrazových záznamov, zvukovo-obrazových záznamov, kníh alebo počítačového softvéru predávaných v ochrannom obale, ak spotrebiteľ tento obal rozbalil,<br>poskytovanie elektronického obsahu inak ako na hmotnom nosiči, ak sa jeho poskytovanie začalo s výslovným súhlasom spotrebiteľa a spotrebiteľ vyhlásil, že bol riadne poučený o tom,<br>že vyjadrením tohto súhlasu stráca právo na odstúpenie od zmluvy.
                           predaj tovaru, ktorý bol v čase po uzavretí zmluvy a prevzatí tovaru od predávajúceho kupujúcemu zmontovaný, zložený alebo použitý takým spôsobom, že jeho opätovné uvedenie do pôvodného stavu predávajúcim nie je možné bez vynaloženia zvýšeného úsilia a zvýšených nákladov, napr. zložený alebo zmontovaný nábytok a pod.
<br><br>
                           <b>12	Záverečné ustanovenia</b><br>
                           12.1	Na vzťahy neupravené týmito Obchodnými a reklamačnými podmienkami sa vzťahujú príslušné ustanovenia Občianskeho zákonníka, zákona č. 22/2004 Z.z. o elektronickom obchode a o zmene a doplnení zákona č. 128/2002 Z.z. o štátnej kontrole vnútorného trhu vo veciach ochrany spotrebiteľa a o zmene a doplnení niektorých zákonov v znení zákona č. 284/2002 Z.z. v znení neskorších predpisov a Zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji na diaľku.<br>
                           12.2	Orgánom dozoru je Slovenská obchodná inšpekcia.<br>
                           12.3	Spotrebiteľ má možnosť obrátiť sa na orgán alternatívneho riešenia spotrebiteľských sporov, ktorý je (i keď len nezáväzne) oprávnený posudzovať prípadné spory medzi Spotrebiteľom ako zákazníkom E-shopu a Prevádzkovateľom E-shopu.<br>
                           12.4	Tieto obchodné a reklamačné podmienky nadobúdajú účinnosť voči Kupujúcemu uzavretím Kúpnej zmluvy.<br><br>
                           <b>13	Rozhodné právo</b><br>
                           13.1	Tieto Obchodné podmienky, ako aj Kúpna zmluva, sa riadia právnym poriadkom Slovenskej republiky.<br><br>
                           <b>14	Účinnosť</b><br>
                           14.1	Tieto Obchodné podmienky sú účinné odo dňa 12.12.2020.


                       </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

<?php include '_inc/footer.php'; ?>